// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkhPcY3kUg5SvTk0tPIXjCLpu6FzpZg5s',
    appId: '1:850444676445:web:9be60f8b28b303ec210cb4',
    messagingSenderId: '850444676445',
    databaseURL: 'https://kidspot-c8914-default-rtdb.asia-southeast1.firebasedatabase.app/',
    projectId: 'kidspot-c8914',
    authDomain: 'kidspot-c8914.firebaseapp.com',
    storageBucket: 'kidspot-c8914.appspot.com',
    measurementId: 'G-N1QW8B4V51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8WusM0Of3L4l0kqtY85DyEfFOKCCiWNE',
    appId: '1:850444676445:android:ef3bf0275bf27bb8210cb4',
    databaseURL: 'https://kidspot-c8914-default-rtdb.asia-southeast1.firebasedatabase.app/',

    messagingSenderId: '850444676445',
    projectId: 'kidspot-c8914',
    storageBucket: 'kidspot-c8914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0K2bLcIrOoNCna78q2UtmRe8x9_Thxio',
    appId: '1:850444676445:ios:1def4146a6d04c31210cb4',
    messagingSenderId: '850444676445',
    projectId: 'kidspot-c8914',
    storageBucket: 'kidspot-c8914.appspot.com',
    databaseURL: 'https://kidspot-c8914-default-rtdb.asia-southeast1.firebasedatabase.app/',

    androidClientId: '850444676445-pdm08192gdo86cocc21hf943e3i5csin.apps.googleusercontent.com',
    iosClientId: '850444676445-8ghpr9c7n43i5l8al9ovujrsg4tonp4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidspotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0K2bLcIrOoNCna78q2UtmRe8x9_Thxio',
    appId: '1:850444676445:ios:91454a561ad6473e210cb4',
    messagingSenderId: '850444676445',
    projectId: 'kidspot-c8914',
    storageBucket: 'kidspot-c8914.appspot.com',
    databaseURL: 'https://kidspot-c8914-default-rtdb.asia-southeast1.firebasedatabase.app/',

    androidClientId: '850444676445-pdm08192gdo86cocc21hf943e3i5csin.apps.googleusercontent.com',
    iosClientId: '850444676445-3sg11ophjnavol03s3khl42s0tps7lel.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidspotApp.RunnerTests',
  );
}
